name: Build + Test w/gcc (Sanitized)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  merge_group:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: apt-get dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install unzip wget cmake lsb-release software-properties-common gnupg ninja-build g++-12 gcc-12
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 16
    - name: CMake
      run: |
        mkdir build
        cd build
        cmake .. -GNinja -DCMAKE_C_COMPILER=gcc-12 -DCMAKE_CXX_COMPILER=g++-12 \
          -DLLVM_CONFIG=llvm-config-16 \
          -DCMAKE_CXX_FLAGS="-fsanitize=address -fsanitize=undefined -ftrivial-auto-var-init=pattern"
    - name: Ninja
      run: |
        cd build
        ninja -j4
    - name: Run test executable
      run: |
        cd build
        ./bin/lang-tests
